### ISSUE TITLE
How do I use tba with React?

### ISSUE THREAD

**Issue by nervetattoo** [webrebels/tba.js#1]
I failed to find information about how to use tba with React.

**Comment by digitalsadhu** [comment]
You need to compile or transpile tba.js first after which it should be able to handle react. We do however recommend (to prevent any runtime errors) that you wait for the elm version which will also include support for hypermedia distribution protocol via IPFS. One caveat is that it will not support server rendering. We expect this version will also include a rewrite to break tba up into tiny modules which we think might help us to support a broader more expressive set of emoji. We are experiencing some hatred toward our test suite but we expect since we have now set a 4 minute test budget that we should be able to get things under control.

Oh and we should have tba.js running on tessel 2 before long as well so keep an eye on that.

Thanks for reporting!
